backend:
  name: git-gateway
  branch: master # 要更新的分支（默认为 master）

# These lines should *not* be indented
media_folder: 'source/img' # 媒体文件将被存储在 source/img下中
public_folder: 'images' # 上传的媒体的src属性将以'images'开头

# This line should *not* be indented
publish_mode: editorial_workflow

collections:
  - name: 'Post' # 在路由中使用，例如，/admin/collections/blog
    label: 'Post' # 在用户界面中使用的 UI
    folder: 'source/_posts' # 储存Post文件的文件夹的路径
    create: true # 是否允许用户在这个集合中创建新的文件
    slug: '{{slug}}' # 文件名模板，例如：YYYY-MM-DD-title.md
    fields: # 每个文件的字段，通常在前面的事项中
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
